### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by jtvanleuven** [edzuf/CrisprOpenDB#8]
Thank you for the great tool. I'm getting an error when running a set of ~450 contigs. I'm trying to determine if a particular contig is causing the error. Thanks.

python CL_Interface.py -i contigs_plasmids_phage.fasta -m 0 -t -n 8 | tee contig_plasmids_phage_predictions.txt

smultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/james/Software/CrisprOpenDB/CrisprOpenDB/CrisprOpenDB_HostID.py", line 137, in _findHost
    fasta_result_table.to_csv("{}.csv".format(fasta_result_table["Query"].iloc[0]))
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "CL_Interface.py", line 42, in <module>
    results = phf.identify(args.input, args.mismatch, args.aligner, args.report, args.table, args.unknown, args.num_threads)
  File "/home/james/Software/CrisprOpenDB/CrisprOpenDB/CrisprOpenDB_HostID.py", line 273, in identify
    results = pool.map(self._findHost, jobs)
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/james/miniconda3/envs/CrisprOpenDB_env/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: single positional indexer is out-of-bounds

**Comment by jtvanleuven** [comment]
I removed the contigs that did not run the first try and reran the program and it did complete, isolating the problem to one of the 27 remaining contigs. I can run these 27 contigs one by one and see where the issue is. Thanks.

**Comment by plpla** [comment]
Hello @jtvanleuven,
we would like to understand why you get this error so that the software can show a useful error message in the future. Would you consider sending us the contig that causes this error? Thanks!
